repos:
  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: poetry run task mypy
        language: system
        pass_filenames: false
      - id: flake8
        name: Run flake8
        entry: poetry run task flake8
        language: system
        pass_filenames: false
      - id: format
        name: Run black (formatting)
        entry: poetry run task format
        language: system
        pass_filenames: false
      - id: export-requirements
        name: Export requirements.txt
        entry: poetry export -f requirements.txt --output requirements.txt --with dev --without-hashes
        language: system
        pass_filenames: false
